# Generated by Django 6.0.6 on 2026-06-21 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_months', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Elo', 'Elo'), ('American Express', 'American Express'), ('Hipercard', 'Hipercard'), ('Outros', 'Outros')], default='Visa', max_length=50)),
                ('closing_day', models.PositiveSmallIntegerField()),
                ('due_day', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cartão',
                'verbose_name_plural': 'cartões',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app_cards.card')),
                ('financial_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_invoices', to='app_months.financialmonth')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ('card__name',),
                'unique_together': {('card', 'financial_month')},
            },
        ),
    ]
