# Generated by Django 6.0.6 on 2026-06-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
    ]
