# Generated by Django 6.0.6 on 2026-06-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0002_cardinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Não pago'), ('paid', 'Pago')], default='unpaid', max_length=15, verbose_name='Status'),
        ),
    ]
