# Generated by Django 6.0.6 on 2026-06-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_months', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financial_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app_months.financialmonth')),
            ],
            options={
                'verbose_name': 'investimento',
                'verbose_name_plural': 'investimentos',
                'ordering': ('-created_at',),
            },
        ),
    ]
