# Generated by Django 6.0.6 on 2026-06-21 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
