# Generated by Django 6.0.6 on 2026-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_installments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='kind',
            field=models.CharField(choices=[('payment', 'Pagamento'), ('sale', 'Venda'), ('loan', 'Empréstimo')], default='payment', max_length=10),
        ),
    ]
