# Generated by Django 6.0.6 on 2026-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_months', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmonth',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmonth',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
