# Generated by Django 6.0.6 on 2026-06-21 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_months', '0002_financialmonth_end_date_financialmonth_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variableexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
