# Generated by Django 6.0.6 on 2026-06-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_months', '0003_entry_date_fixedexpense_date_variableexpense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpense',
            name='date',
        ),
    ]
